# Compose file 
version: "3"

services:
  proxy:
    build: ./proxy/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - /var/log/nginx
  web:
    build: ./web/
    ports:
      - "7000"
      